Repository scopeseeker/scopeseeker-frontend, pull requests merged in 2023-07, with the labels that each got.

#241 style: Ui design of contact us page updated
  pages/contact-us.tsx
  public/assets/images/location.png
Labels: style

#242 contact us page ui design updated
  pages/contact-us.tsx
Labels: style

#243 style: contact us page responsive done
  pages/contact-us.tsx
Labels: style

#244 style: hiring process tab pannel added in company detail
  pages/company/details/[slug].tsx
  section-components/comapany-details/HiringProcess.tsx
  section-components/index.js
Labels: style

#248 improve auth code structure and use auth layout
  app/(auth)/AuthLayout.tsx
  app/(auth)/login/loading.tsx
  app/(auth)/login/login.tsx
  app/(auth)/login/page.tsx
  app/(auth)/signup/loading.tsx
  app/(auth)/signup/page.tsx
  app/(auth)/signup/signup.tsx
  app/all-pages/page.tsx
  app/login/login.tsx
  app/login/page.tsx
  app/provider.tsx
  app/settings/settings.tsx
  app/signup/signup.tsx
  section-components/otp-verify-box/OtpVerifyBox.tsx
Labels: code refactor

#250 contact us page updated
  app/contact-us/contact-us.tsx
Labels: style

#251 feat: Add form and validation functionality to login component
  app/(auth)/login/login.tsx
  package.json
  yarn.lock
Labels: help wanted, feat

#252 Code refactor
  app/(auth)/login/login.tsx
  app/all-pages/page.tsx
  app/blogs/[slug]/blog.tsx
  app/blogs/blogs.tsx
  app/company/company.tsx
  app/company/details/[slug]/company-details.tsx
  app/jobs/details/[slug]/MoreJobs.tsx
  app/jobs/jobs.tsx
  app/resources/[slug]/MoreResource.tsx
  component/badge/MyBadge.tsx
  component/filter/Filter.tsx
  component/radio-buttons/RadioButton.tsx
  constant/constantFields.ts
  package.json
  section-components/comapany-details/Benifits.tsx
  section-components/comapany-details/Overview.tsx
  section-components/edit-profile/BasicInformationSection.tsx
  section-components/first-page-sections/FAQ.tsx
  section-components/first-page-sections/FeaturedCompany.tsx
  section-components/first-page-sections/PopularCategories.tsx
Labels: code refactor

#253 remove prettier from pre-commit
  .eslintrc.json
  package.json
Labels: code refactor

#254 refactor: metadata changes of all pages
  app/blogs/page.tsx
  app/company/page.tsx
  app/contact-us/page.tsx
  app/dashboard/page.tsx
  app/edit-profile/page.tsx
  app/jobs/page.tsx
  app/legal/privacy-policy/page.tsx
  app/legal/terms-of-use/page.tsx
  app/my-profile/page.tsx
  app/request-company/page.tsx
  app/resources/page.tsx
  constant/metaData.ts
Labels: code refactor

#255 ref: refactor some code
  section-components/first-page-sections/HowWorks.tsx
Labels: style, code refactor

#256 Code refactor
  app/(auth)/AuthLayout.tsx
  app/(auth)/login/login.tsx
  app/(auth)/signup/signup.tsx
  app/blogs/[slug]/blog.tsx
  app/request-company/request-company.tsx
  app/settings/settings.tsx
  component/inputs/MyInput.tsx
  inteface/component-interface.ts
  section-components/comapany-details/JobTab.tsx
  section-components/edit-profile/EducationSection.tsx
  section-components/edit-profile/SkillsSection.tsx
  section-components/edit-profile/SocialLinksSection.tsx
  section-components/edit-profile/WorkExperienceSection.tsx
  styles/theme.ts
Labels: code refactor

#259 responsive: helpful resources and resources page responsive ui done
  src/app/resources/[slug]/MoreResource.tsx
  src/app/resources/resources.tsx
Labels: style

#260 responsive: resources and more resources responsive fix
  src/app/resources/[slug]/MoreResource.tsx
  src/app/resources/resources.tsx
Labels: style

#261 feat: Implement form validation for login form
  src/app/(auth)/login/login.tsx
  src/helpers/toast.tsx
  src/helpers/validationSchema.ts
  src/helpers/validator.ts
  src/section-components/cards/MyArticleCard.tsx
  src/section-components/cards/MyCompanyCard.tsx
  src/section-components/comapany-details/Benifits.tsx
  src/section-components/edit-profile/BasicInformationSection.tsx
  src/section-components/first-page-sections/Testimonials.tsx
Labels: feat

#262 style: refactor some code
  src/app/jobs/jobs.tsx
  src/component/filter/Filter.tsx
  src/constant/constantFields.ts
Labels: style, code refactor

#264 form-validation: validation of request a company page done
  src/app/request-company/request-company.tsx
  src/helpers/validationSchema.ts
Labels: feat

#265 validation: validation of request a company bug fixed
  src/app/request-company/request-company.tsx
Labels: bug

#266 form-validation: edit-profile validation done
  src/helpers/validationSchema.ts
  src/section-components/edit-profile/BasicInformationSection.tsx
  src/section-components/edit-profile/SocialLinksSection.tsx
Labels: feat

#267 rfc: improve validationSchema code and resolve bug of request page
  src/app/contact-us/contact-us.tsx
  src/app/request-company/request-company.tsx
  src/helpers/validationSchema.ts
  src/section-components/page-header/PageHeader.tsx
Labels: code refactor

#268 feat: edit profile basic information form validaiton apply
  src/app/(auth)/login/login.tsx
  src/app/(auth)/signup/signup.tsx
  src/app/edit-profile/edit-profile.tsx
  src/component/radio-buttons/RadioButton.tsx
  src/helpers/validationSchema.ts
  src/section-components/edit-profile/BasicInformationSection.tsx
  src/section-components/edit-profile/LeftEditProfilePart.tsx
  src/section-components/edit-profile/SocialLinksSection.tsx
Labels: feat

#269 ref: refactor some code
  src/constant/IconLibrary.tsx
  src/section-components/first-page-sections/HowWorks.tsx
  src/section-components/first-page-sections/PopularCategories.tsx
  src/section-components/footer/Footer.tsx
  src/section-components/navbar/Navbar.tsx
Labels: style, code refactor

#270 style: contact-us responsive done
  src/app/contact-us/contact-us.tsx
Labels: style, code refactor

#271 form-validation: work experience part validated
  src/helpers/validationSchema.ts
  src/section-components/edit-profile/WorkExperienceSection.tsx
Labels: feat

#272 fix: avatar menu navbar box close issue fixed
  src/constant/linksObject.ts
  src/section-components/edit-profile/BasicInformationSection.tsx
  src/section-components/navbar/Navbar.tsx
Labels: bug

#273 form-validation: education section validated
  src/helpers/validationSchema.ts
  src/section-components/edit-profile/EducationSection.tsx
  src/section-components/edit-profile/templates/AddBoxTemplate.tsx
Labels: feat

#274 fix: education form validation error fix
  src/component/button/MyButton.tsx
  src/helpers/validationSchema.ts
  src/inteface/component-interface.ts
  src/section-components/edit-profile/EducationSection.tsx
Labels: bug

#275 feat: add scroll effect on edit profile
  src/section-components/edit-profile/BasicInformationSection.tsx
  src/section-components/edit-profile/EducationSection.tsx
  src/section-components/edit-profile/LeftEditProfilePart.tsx
  src/section-components/edit-profile/ResumeSection.tsx
  src/section-components/edit-profile/SkillsSection.tsx
  src/section-components/edit-profile/SocialLinksSection.tsx
  src/section-components/edit-profile/WorkExperienceSection.tsx
  src/section-components/edit-profile/templates/SectionTemplate.tsx
  src/styles/globals.css
Labels: feat

#276 feat: Upload resume feature added
  src/section-components/edit-profile/ResumeSection.tsx
Labels: feat

#277 style: refactor some code and change icon in about-us
  src/app/about-us/about-us.tsx
Labels: style, code refactor

#278 ref: refactor some code in testimonials
  src/section-components/first-page-sections/Testimonials.tsx
Labels: code refactor

#279 refactor-components: add and cancel option updated.
  src/constant/IconLibrary.tsx
  src/section-components/edit-profile/EducationSection.tsx
Labels: feat

#280 Code refactor
  src/app/(auth)/AuthLayout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/about-us/page.tsx
  src/app/blogs/page.tsx
  src/app/layout.tsx
  src/app/legal/terms-of-use/page.tsx
  src/app/page.tsx
  src/app/settings/page.tsx
  src/component/text/MyText.tsx
  src/constant/constantFields.ts
  src/constant/metaData.ts
  src/inteface/component-interface.ts
  src/section-components/footer/Footer.tsx
  src/section-components/index.js
  src/section-components/logo/ScopeSeekerLogo.tsx
  src/section-components/navbar/Navbar.tsx
Labels: code refactor

#281 ref: refactor code of workExperience and other sections
  src/app/dashboard/dashboard.tsx
  src/section-components/edit-profile/BasicInformationSection.tsx
  src/section-components/edit-profile/WorkExperienceSection.tsx
Labels: style, code refactor

#282 feat: Implement Google OAuth login
  .env
  package.json
  src/app/(auth)/AuthLayout.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/dashboard/dashboard.tsx
  src/app/provider.tsx
  src/middleware.ts
  src/section-components/navbar/Navbar.tsx
  src/utils/authOptions.ts
  yarn.lock
Labels: feat

#283 feat: implement mongodb
  .env
  package.json
  src/app/api/post/route.ts
  src/middleware.ts
  src/models/userSchema.ts
  src/utils/db.ts
  yarn.lock
Labels: feat

#284 feat: signin with google data store in database
  .env
  src/app/api/signup/route.ts
  src/app/dashboard/dashboard.tsx
  src/utils/authOptions.ts
Labels: feat

#285 ref: refactor code and make data fields in edit-profile
  src/constant/basic-information/data.ts
  src/helpers/validationSchema.ts
  src/section-components/edit-profile/BasicInformationSection.tsx
  src/section-components/edit-profile/EducationSection.tsx
  src/section-components/edit-profile/WorkExperienceSection.tsx
Labels: code refactor, feat

#286 rfc: improve error handling in signup route
  src/app/(auth)/AuthLayout.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/signup/route.ts
  src/lib/authOptions.ts
  src/lib/db.ts
  src/section-components/navbar/Navbar.tsx
  src/utils/db.ts
Labels: feat

#287 ref: refactor code of edit-profile
  src/constant/basic-information/data.ts
  src/section-components/edit-profile/BasicInformationSection.tsx
  src/section-components/edit-profile/EducationSection.tsx
Labels: code refactor

#288 rfc: improved the validation of user schema
  next.config.js
  src/app/(auth)/signup/signup.tsx
  src/app/api/signup/route.ts
  src/lib/authOptions.ts
  src/models/userSchema.ts
  src/section-components/navbar/Navbar.tsx
Labels: backend

#289 refactor filter components
  src/app/company/company.tsx
  src/app/jobs/jobs.tsx
  src/constant/constantFields.ts
  src/constant/filterConstant.ts
Labels: code refactor

#290 ref: change file name and refactor some code
  src/constant/editProfileData.ts
  src/section-components/edit-profile/BasicInformationSection.tsx
  src/section-components/edit-profile/EducationSection.tsx
  src/section-components/edit-profile/WorkExperienceSection.tsx
Labels: code refactor

#291 feat: add signup with email auth
  .eslintrc.json
  package.json
  src/app/(auth)/login/login.tsx
  src/app/(auth)/signup/signup.tsx
  src/app/api/signup/route.ts
  src/component/button/MyButton.tsx
  src/helpers/validationSchema.ts
  src/lib/authOptions.ts
  src/models/userSchema.ts
  yarn.lock
Labels: feat, backend

#292 feat: Add companySchema file inside model
  src/app/api/user/route.ts
  src/models/companySchema.ts
  src/models/userSchema.ts
Labels: feat, backend

#293 rfc: improve companySchema fields
  package.json
  src/models/companySchema.ts
  yarn.lock
Labels: database
